# Generated by Django 2.2.2 on 2019-06-20 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='number_day',
        ),
    ]
