# Generated by Django 2.2.2 on 2019-06-20 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0002_remove_workday_number_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduleWork',
        ),
    ]
