# Generated by Django 2.2.2 on 2019-06-23 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0004_auto_20190622_1711'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='date_day',
        ),
    ]
