# Generated by Django 2.2.2 on 2019-06-23 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0005_remove_workday_date_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='date_day',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='workday',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
