# Generated by Django 2.2.2 on 2019-06-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0006_auto_20190623_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='start_date',
        ),
    ]
