# Generated by Django 2.2.2 on 2019-06-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0007_auto_20190623_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='workday',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workday',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='date_day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
