# Generated by Django 2.2.2 on 2019-06-25 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0008_auto_20190624_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workday',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='workday',
            name='start_date',
        ),
    ]
