# Generated by Django 2.2.2 on 2019-06-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkShedule', '0010_workday_date_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workday',
            name='time_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workday',
            name='time_start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
